# FinAccess 2021 Microdata Exploration

This note book explores the srtucture of the FinAccess 2021 Microdata Excel Workbook, inspects variables, creates a variable dictionary, and identifies possible target variables for financial inclusion analysis.

# Abstract

This project focuses on predicting exclusion risk among Kenyan adults using machine learning and explainable AI techniques. Although Kenya is widely known for mobile money, many people still lack access to formal finacial services such as banks, insurance, SACCOs, pensions and regulated credit products. The goal of this project is to identifiy individuals who are most at risk of financial exclusion, understand the main factors contributing to that risk, and analyze how exclusion, patterns vary across counties and vulnerable groups in Kenya.

The project will use the 2021 FinAccess Household Survey microdata as the maiin dataset, while the 2024 FinAccess report and dashboard will be used for comparison and interpretation of trends. Several machine learning models, including Logistic Regression, Decision Trees, Random Forest,Gradient Boosting, and XGBoost. will be explored and evalluated using performance metrics such as accuracy, precision, recall, F1-score, and ROC-AUC. SHAP explainability techniques will also be used to show the key factors influencing financial exclusion predictions.

In addition to predictive modeling, the project will include county-level risk mapping, sub-group analysis, and the development of a Flask web application that provides financial exclusion probability scores, risk tiers, and key contributing factors. The findings from this project cold help banks, fintech companies, Saccos, policy makers, and development organizations design more targeted financial inclusion strategies and interventions across kenya.

In [2]:
import pandas as pd 
import openpyxl 
import os

print(openpyxl.__version__)
print(os.listdir())


# Load the Excel file
excel_file = pd.ExcelFile("../data/raw/finaccess_2021_microdata.xlsx")

# View sheet names
print(excel_file.sheet_names)

# Load the first sheet
df = pd.read_excel("../data/raw/finaccess_2021_microdata.xlsx", sheet_name="Dataset",nrows=1000,engine="openpyxl")
df.head()

ImportError: DLL load failed while importing _multiarray_umath: The specified module could not be found.

3.1.5
['01_data _understanding.ipynb', 'dummy.ipynb.txt']
['Dataset', 'Variable Information', 'Variable Values']

,Serial Number,County,ClusterNo,HHNo,interview__key,interview__id,A9,A9i,A10i,A14v,...,allotherformal_banked2022,formal_banked2022,excluded_informal_banked2022,NHIF_health_insurance,NHIF_ONLY,Medical_Insurance_ONLY,BothNHIF_medical,Nomedical,NHIFMedical_Cat,adults
0,1,Trans Nzoia,10226038,1048,10-67-89-46,0003fc74b3fe418ea041bd6a9e7ff387,Rural,Access granted,Female,1,...,Yes,No,Other Formal,Yes,NaN,NaN,1.0,NaN,Users of NHIF + medical insurance (C1_42 and C...,1 adult Household
1,2,Busia,10240034,1080,39-64-68-81,0004890b17744272baf0a0c7b4c20771,Rural,Access granted,Female,4,...,No,Yes,Banked,Yes,1.0,NaN,NaN,NaN,"Users of NHIF only, with no medical insurance",>1 adult Household
2,3,Machakos,10216062,1013,92-34-74-01,00052153fe8c4abaa189caadcb87b2b4,Rural,Access granted,Male,1,...,No,No,Excluded,Yes,1.0,NaN,NaN,NaN,"Users of NHIF only, with no medical insurance",1 adult Household
3,4,Kisumu,10242078,1026,08-14-22-63,000d1f8747194b6a84862830dc5fe7ca,Rural,Access granted,Male,5,...,No,Yes,Banked,No,NaN,NaN,NaN,"Users of NHIF only, with no medical insurance",None users of any of NHIF and medical insurance,>1 adult Household
4,5,Nyeri,10219138,1019,99-12-05-84,000f5a5c0e3246ac9a62603ad936e3da,Urban,Access granted,Male,3,...,No,Yes,Banked,No,NaN,NaN,NaN,"Users of NHIF only, with no medical insurance",None users of any of NHIF and medical insurance,>1 adult Household

In [ ]:
df.shape

(1000, 2332)

In [ ]:
df.columns

Index(['Serial Number', 'County', 'ClusterNo', 'HHNo', 'interview__key',
       'interview__id', 'A9', 'A9i', 'A10i', 'A14v',
       ...
       'allotherformal_banked2022', 'formal_banked2022',
       'excluded_informal_banked2022', 'NHIF_health_insurance', 'NHIF_ONLY',
       'Medical_Insurance_ONLY', 'BothNHIF_medical', 'Nomedical',
       'NHIFMedical_Cat', 'adults'],
      dtype='object', length=2332)

In [ ]:
df.describe()

,Serial Number,ClusterNo,HHNo,A14v,A14vi,A17,A19,A21i,B3Di.2,B3Di.3,...,non_Informal_only_credit_users2,NotFormal_non_digital_only,all_loans,received1,sent1,loan_Traditional,informal_sector,NHIF_ONLY,Medical_Insurance_ONLY,BothNHIF_medical
count,1000.000000,1.000000e+03,1000.000000,1000.00000,1000.000000,1000.000000,1000.000000,0.0,0.0,0.0,...,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000,1000.000000,1000.000000,155.0,25.0,6.0
mean,500.500000,1.020131e+07,1053.782000,2.39000,1.754000,0.097000,38.907000,NaN,NaN,NaN,...,0.241000,0.488000,0.37200,0.915000,0.844000,0.031000,0.660000,1.0,1.0,1.0
std,288.819436,4.528596e+04,36.683404,1.40637,1.216126,0.517551,16.948971,NaN,NaN,NaN,...,0.427904,0.500106,0.48358,0.279021,0.363037,0.173404,0.473946,0.0,0.0,0.0
min,1.000000,1.010103e+07,1001.000000,1.00000,1.000000,0.000000,16.000000,NaN,NaN,NaN,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,1.0,1.0,1.0
25%,250.750000,1.020110e+07,1025.000000,1.00000,1.000000,0.000000,26.000000,NaN,NaN,NaN,...,0.000000,0.000000,0.00000,1.000000,1.000000,0.000000,0.000000,1.0,1.0,1.0
50%,500.500000,1.021806e+07,1048.000000,2.00000,1.000000,0.000000,35.000000,NaN,NaN,NaN,...,0.000000,0.000000,0.00000,1.000000,1.000000,0.000000,1.000000,1.0,1.0,1.0
75%,750.250000,1.023439e+07,1075.000000,3.00000,2.000000,0.000000,49.000000,NaN,NaN,NaN,...,0.000000,1.000000,1.00000,1.000000,1.000000,0.000000,1.000000,1.0,1.0,1.0
max,1000.000000,1.024729e+07,1236.000000,10.00000,11.000000,6.000000,91.000000,NaN,NaN,NaN,...,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.0,1.0,1.0

## Dataset sheet

This sheet contains the actual survey responses collected from respondents during he 2021 FinAccess survey.

In [7]:
# Load the second sheet
df = pd.read_excel("../data/raw/finaccess_2021_microdata.xlsx", sheet_name="Variable Information", nrows=1000, engine="openpyxl",header=1)
df.head()

,Variable,Position,Label,Column Width,Write Format,Missing Values
0,County,1,County,8,F12,NaN
1,ClusterNo,2,A7. NASSEP Cluster Number,18,F12,NaN
2,HHNo,3,A8. Household Number,18,F12,NaN
3,interview__key,4,Interview key (identifier in XX-XX-XX-XX format),33,A99,NaN
4,interview__id,5,Unique 32-character long identifier of the int...,50,A288,NaN

In [4]:
df.shape

(1000, 6)

In [5]:
df.columns

Index(['Variable Information', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3',
       'Unnamed: 4', 'Unnamed: 5'],
      dtype='object')

## Variable Information Sheet Description
This sheet provides definitions and descriptions for variables contained in the dataset sheet. It helps explain what each column represents.

## Important Variables Dictionary
The variable information sheet contains descriptions of variables used in the dataset. This section creates a variable dictionary to help interpret important variables and understand their meaning during analysis.

In [9]:
#Load Variable Information sheet
variable_info_df = pd.read_excel("../data/raw/finaccess_2021_microdata.xlsx",sheet_name="Variable Information",engine="openpyxl",header=1)

#create variable dictionary
variable_dict = dict(zip(variable_info_df["Variable"], variable_info_df["Label"]))

#display variable dictionary
variable_dict

{'County': 'County',
 'ClusterNo': 'A7. NASSEP Cluster Number',
 'HHNo': 'A8. Household Number',
 'interview__key': 'Interview key (identifier in XX-XX-XX-XX format)',
 'interview__id': 'Unique 32-character long identifier of the interview',
 'A9': 'A9. Cluster type',
 'A9i': 'A9i. What was the RESULTS of this interview?',
 'A10i': 'A10i. Sex',
 'A14v': 'A14v Number of eligible persons',
 'A14vi': 'A14vi Index of the selected person',
 'A15': 'A15. Language',
 'A15i': 'A15i. Language',
 'A17': 'A17. Not returned to complete their education',
 'A18': 'A17. Selected Respondent sex',
 'A19': 'A19. AGE OF RESPONDENT',
 'A20': 'A20. Relation to HH Head',
 'A21': 'A21. Education Completed',
 'A21i': 'A21i. Other Education level Completed',
 'A22': 'A22. Marital Status',
 'A23': 'A23. Female HH Highest Formal Education',
 'A24': 'A24. Chronic Disease',
 'A25': 'A25. Persons with disability',
 'A26__1': 'A26. Persons with disability:Difficulty in seeing',
 'A26__2': 'A26. Persons with disability:Difficulty in hearing',
 'A26__3': 'A26. Persons with disability:Difficulty in walking or climbing steps (mobility)',
 'A26__4': 'A26. Persons with disability:Difficulty in remembering or concentration',
 'A26__5': 'A26. Persons with disability:Difficulty in self-care e.g. washing all over or dressing',
 'A26__6': 'A26. Persons with disability:Difficulty in communicating using your usual language',
 'B1A': 'B1A. Main Life Goal',
 'B1B1': 'B1B1 People in your life',
 'B1B2': 'B1B2. Keep money aside?',
 'B1B3': 'B1B3. Spending plan',
 'B1B4': 'B1B4. Loan Security',
 'B1B5': 'B1B5. Overcome Financial problems',
 'B1C1': 'B1C1 Frequency gone without enough food to eat',
 'B1C2': 'B1C2. Frequency gone without medicine or medical treatment',
 'B1C3': 'B1C3. Frequency miss an important family event',
 'B1C4': 'B1C4.Frequency Child or any person you support  sent home for lack of school fee',
 'B1D': 'B1D. Financial decisions Maker-Large',
 'B1EF1': 'B1EF1. Draw on savings',
 'B1EF2': 'B1EF2. Drawing on pension/annuity or access retirement savings',
 'B1EF3': 'B1EF3. Rely on children or other family',
 'B1EF4': 'B1EF4. Run my own business',
 'B1EF5': 'B1EF5. Sell assets',
 'B1EF6': 'B1EF6. Income from investments (e.g shares,rental)',
 'B1EF7': 'B1EF7. Live off the farm',
 'B1EF8': 'B1EF8. Government fund for the old e.g Older persons(OPCT)',
 'B1EF9': 'B1EF9. Other (Specify)',
 'B1EF10': 'B1EF10. Don’t know how / Have no plans',
 'B1EF11': 'B1EF11. Employment',
 'B1EF98': "B1EF98. Don't know (DO NOT READ OUT)",
 'B1EF99': 'B1EF99. Refused to Answer(DO NOT READ OUT)',
 'B1G': 'B1G. Remained Same or Worsened',
 'B1H_I': 'B1H. Access in Case of Emergency_Urban/Rural',
 'B1J': 'B1J. Source Emergency Funds',
 'B1K': 'B1K. Access in Case of Emergency',
 'B2A': 'B2A. Financial Advice',
 'B2B': 'B2B. Heard of CRB Report',
 'B2C': 'B2C. Access CRB Report',
 'B2D': 'B2D. Agree or Disagree Statements- Gaming',
 'B2E': 'B2E. Gaming',
 'B2F': 'B2F. Interest Paid Answer',
 'B2G': 'B2G. Can Read SMS',
 'B3A__1': 'B3A. Income Sources:farming (crops, keeping livestock, fishing, aquaculture)',
 'B3A__2': 'B3A. Income Sources:employment',
 'B3A__3': 'B3A. Income Sources:casual work',
 'B3A__4': 'B3A. Income Sources:running own business/Self employment',
 'B3A__5': 'B3A. Income Sources:money from  NGO / Government/Social transfer',
 'B3A__6': 'B3A. Income Sources:renting,  land, house/rooms, equipment',
 'B3A__7': 'B3A. Income Sources:Earning money from investments, e.g. shares, stocks',
 'B3A__8': 'B3A. Income Sources:Pension/Annuity',
 'B3A__9': 'B3A. Income Sources:Money / support from family / friends / spouse',
 'B3B': 'B3B. Main Source',
 'B3C': 'B3C. Subsistence Answer',
 'B3D__1.1': 'B3D__1.1  Cash:1 farming (crops, keeping livestock, fishing, aquaculture)',
 'B3D__1.2': 'B3D__1.2  Cash:2 employment',
 'B3D__1.3': 'B3D__1.3  Cash:3 casual work',
 'B3D__1.4': 'B3D__1.4  Cash:4 running own business/Self employment',
 'B3D__1.5': 'B3D__1.5  Cash:5 money from  NGO / Government/Social transfer',
 'B3D__1.6': 'B3D__1.6  Cash:6 renting,  land, house/rooms, equipment',
 'B3D__1.7': 'B3D__1.7  Cash:7 Earning money from investments, e.g. shares, stocks',
 'B3D__1.8': 'B3D__1.8  Cash:8 Pension/Annuity',
 'B3D__1.9': 'B3D__1.9  Cash:9 Money / support from family / friends / spouse',
 'B3D__2.1': 'B3D__2.1  Mobile money:1 farming (crops, keeping livestock, fishing, aquaculture)',
 'B3D__2.2': 'B3D__2.2  Mobile money:2 employment',
 'B3D__2.3': 'B3D__2.3  Mobile money:3 casual work',
 'B3D__2.4': 'B3D__2.4  Mobile money:4 running own business/Self employment',
 'B3D__2.5': 'B3D__2.5  Mobile money:5 money from  NGO / Government/Social transfer',
 'B3D__2.6': 'B3D__2.6  Mobile money:6 renting,  land, house/rooms, equipment',
 'B3D__2.7': 'B3D__2.7  Mobile money:7 Earning money from investments, e.g. shares, stocks',
 'B3D__2.8': 'B3D__2.8  Mobile money:8 Pension/Annuity',
 'B3D__2.9': 'B3D__2.9  Mobile money:9 Money / support from family / friends / spouse',
 'B3D__3.1': 'B3D__3.1  Bank cheque:1 farming (crops, keeping livestock, fishing, aquaculture)',
 'B3D__3.2': 'B3D__3.2  Bank cheque:2 employment',
 'B3D__3.3': 'B3D__3.3  Bank cheque:3 casual work',
 'B3D__3.4': 'B3D__3.4  Bank cheque:4 running own business/Self employment',
 'B3D__3.5': 'B3D__3.5  Bank cheque:5 money from  NGO / Government/Social transfer',
 'B3D__3.6': 'B3D__3.6  Bank cheque:6 renting,  land, house/rooms, equipment',
 'B3D__3.7': 'B3D__3.7  Bank cheque:7 Earning money from investments, e.g. shares, stocks',
 'B3D__3.8': 'B3D__3.8  Bank cheque:8 Pension/Annuity',
 'B3D__3.9': 'B3D__3.9  Bank cheque:9 Money / support from family / friends / spouse',
 'B3D__4.1': 'B3D__4.1  Bank transfer (e.g. EFT, SWIFT, Pesalink) / Bank deposit:1 farming (crops, keeping livestock, fishing, aquaculture)',
 'B3D__4.2': 'B3D__4.2  Bank transfer (e.g. EFT, SWIFT, Pesalink) / Bank deposit:2 employment',
 'B3D__4.3': 'B3D__4.3  Bank transfer (e.g. EFT, SWIFT, Pesalink) / Bank deposit:3 casual work',
 'B3D__4.4': 'B3D__4.4  Bank transfer (e.g. EFT, SWIFT, Pesalink) / Bank deposit:4 running own business/Self employment',
 'B3D__4.5': 'B3D__4.5  Bank transfer (e.g. EFT, SWIFT, Pesalink) / Bank deposit:5 money from  NGO / Government/Social transfer',
 'B3D__4.6': 'B3D__4.6  Bank transfer (e.g. EFT, SWIFT, Pesalink) / Bank deposit:6 renting,  land, house/rooms, equipment',
 'B3D__4.7': 'B3D__4.7  Bank transfer (e.g. EFT, SWIFT, Pesalink) / Bank deposit:7 Earning money from investments, e.g. shares, stocks',
 'B3D__4.8': 'B3D__4.8  Bank transfer (e.g. EFT, SWIFT, Pesalink) / Bank deposit:8 Pension/Annuity',
 'B3D__4.9': 'B3D__4.9  Bank transfer (e.g. EFT, SWIFT, Pesalink) / Bank deposit:9 Money / support from family / friends / spouse',
 'B3D__5.1': 'B3D__5.1  Credit cards / debit cards:1 farming (crops, keeping livestock, fishing, aquaculture)',
 'B3D__5.2': 'B3D__5.2  Credit cards / debit cards:2 employment',
 'B3D__5.3': 'B3D__5.3  Credit cards / debit cards:3 casual work',
 'B3D__5.4': 'B3D__5.4  Credit cards / debit cards:4 running own business/Self employment',
 'B3D__5.5': 'B3D__5.5  Credit cards / debit cards:5 money from  NGO / Government/Social transfer',
 'B3D__5.6': 'B3D__5.6  Credit cards / debit cards:6 renting,  land, house/rooms, equipment',
 'B3D__5.7': 'B3D__5.7  Credit cards / debit cards:7 Earning money from investments, e.g. shares, stocks',
 'B3D__5.8': 'B3D__5.8  Credit cards / debit cards:8 Pension/Annuity',
 'B3D__5.9': 'B3D__5.9  Credit cards / debit cards:9 Money / support from family / friends / spouse',
 'B3D__6.1': 'B3D__6.1  Inkind payments in goods and/or services:1 farming (crops, keeping livestock, fishing, aquaculture)',
 'B3D__6.2': 'B3D__6.2  Inkind payments in goods and/or services:2 employment',
 'B3D__6.3': 'B3D__6.3  Inkind payments in goods and/or services:3 casual work',
 'B3D__6.4': 'B3D__6.4  Inkind payments in goods and/or services:4 running own business/Self employment',
 'B3D__6.5': 'B3D__6.5  Inkind payments in goods and/or services:5 money from  NGO / Government/Social transfer',
 'B3D__6.6': 'B3D__6.6  Inkind payments in goods and/or services:6 renting,  land, house/rooms, equipment',
 'B3D__6.7': 'B3D__6.7  Inkind payments in goods and/or services:7 Earning money from investments, e.g. shares, stocks',
 'B3D__6.8': 'B3D__6.8  Inkind payments in goods and/or services:8 Pension/Annuity',
 'B3D__6.9': 'B3D__6.9  Inkind payments in goods and/or services:9 Money / support from family / friends / spouse',
 'B3D__7.1': 'B3D__7.1  Digital /communitycurrency e.g bitcoin, bangla pesa:1 farming (crops, keeping livestock, fishing, aquaculture)',
 'B3D__7.2': 'B3D__7.2  Digital /communitycurrency e.g bitcoin, bangla pesa:2 employment',
 'B3D__7.3': 'B3D__7.3  Digital /communitycurrency e.g bitcoin, bangla pesa:3 casual work',
 'B3D__7.4': 'B3D__7.4  Digital /communitycurrency e.g bitcoin, bangla pesa:4 running own business/Self employment',
 'B3D__7.5': 'B3D__7.5  Digital /communitycurrency e.g bitcoin, bangla pesa:5 money from  NGO / Government/Social transfer',
 'B3D__7.6': 'B3D__7.6  Digital /communitycurrency e.g bitcoin, bangla pesa:6 renting,  land, house/rooms, equipment',
 'B3D__7.7': 'B3D__7.7  Digital /communitycurrency e.g bitcoin, bangla pesa:7 Earning money from investments, e.g. shares, stocks',
 'B3D__7.8': 'B3D__7.8  Digital /communitycurrency e.g bitcoin, bangla pesa:8 Pension/Annuity',
 'B3D__7.9': 'B3D__7.9  Digital /communitycurrency e.g bitcoin, bangla pesa:9 Money / support from family / friends / spouse',
 'B3D__8.1': 'B3D__8.1  Other (SPECIFY):1 farming (crops, keeping livestock, fishing, aquaculture)',
 'B3D__8.2': 'B3D__8.2  Other (SPECIFY):2 employment',
 'B3D__8.3': 'B3D__8.3  Other (SPECIFY):3 casual work',
 'B3D__8.4': 'B3D__8.4  Other (SPECIFY):4 running own business/Self employment',
 'B3D__8.5': 'B3D__8.5  Other (SPECIFY):5 money from  NGO / Government/Social transfer',
 'B3D__8.6': 'B3D__8.6  Other (SPECIFY):6 renting,  land, house/rooms, equipment',
 'B3D__8.7': 'B3D__8.7  Other (SPECIFY):7 Earning money from investments, e.g. shares, stocks',
 'B3D__8.8': 'B3D__8.8  Other (SPECIFY):8 Pension/Annuity',
 'B3D__8.9': 'B3D__8.9  Other (SPECIFY):9 Money / support from family / friends / spouse',
 'B3D__98.1': "B3D__98.1  Don't know(DO NOT READ OUT):1 farming (crops, keeping livestock, fishing, aquaculture)",
 'B3D__98.2': "B3D__98.2  Don't know(DO NOT READ OUT):2 employment",
 'B3D__98.3': "B3D__98.3  Don't know(DO NOT READ OUT):3 casual work",
 'B3D__98.4': "B3D__98.4  Don't know(DO NOT READ OUT):4 running own business/Self employment",
 'B3D__98.5': "B3D__98.5  Don't know(DO NOT READ OUT):5 money from  NGO / Government/Social transfer",
 'B3D__98.6': "B3D__98.6  Don't know(DO NOT READ OUT):6 renting,  land, house/rooms, equipment",
 'B3D__98.7': "B3D__98.7  Don't know(DO NOT READ OUT):7 Earning money from investments, e.g. shares, stocks",
 'B3D__98.8': "B3D__98.8  Don't know(DO NOT READ OUT):8 Pension/Annuity",
 'B3D__98.9': "B3D__98.9  Don't know(DO NOT READ OUT):9 Money / support from family / friends / spouse",
 'B3D__99': 'B3D__99  Refused to Answer (DO NOT READ OUT)',
 'B3Di.1': '1 farming (crops, keeping livestock, fishing, aquaculture)',
 'B3Di.2': '2 employment',
 'B3Di.3': '3 casual work',
 'B3Di.4': '4 running own business/Self employment',
 'B3Di.5': '5 money from  NGO / Government/Social transfer',
 'B3Di.6': '6 renting,  land, house/rooms, equipment',
 'B3Di.7': '7 Earning money from investments, e.g. shares, stocks',
 'B3Di.8': '8 Pension/Annuity',
 'B3Di.9': '9 Money / support from family / friends / spouse',
 'B3E.1': '1 farming (crops, keeping livestock, fishing, aquaculture)',
 'B3E.2': '2 employment',
 'B3E.3': '3 casual work',
 'B3E.4': '4 running own business/Self employment',
 'B3E.5': '5 money from  NGO / Government/Social transfer',
 'B3E.6': '6 renting,  land, house/rooms, equipment',
 'B3E.7': '7 Earning money from investments, e.g. shares, stocks',
 'B3E.8': '8 Pension/Annuity',
 'B3E.9': '9 Money / support from family / friends / spouse',
 'B3F': 'B3F. Type of Work',
 'B3Fi': 'B3Fi. Other type of Work',
 'B3G': 'B3G. Private or Public Sector Employment',
 'B3H1': 'B3H1. Orphans and vulnerable (CTOVC)',
 'B3H2': 'B3H2. Older persons (OPCT)',
 'B3H3': 'B3H3. Disabilities (CTPWSD)',
 'B3H4': 'B3H4. Hunger and Safety Net Programme (HSNP)',
 'B3H5': 'B3H5. Covid19 pandemic relief',
 'B3H6': 'B3H6. Government Assistance',
 'B3H7': 'B3H7. Other government',
 'B3H8': 'B3H8. Private sector/NGO',
 'B3I': 'B3I. Monthly Income (KSh)',
 'C1_1': 'C1-1. Microfinance institution',
 'C1_2': 'C1-2. Savings through mobile banking (e.g. Mshwari , KCB MPesa, MCoop cash, Eazzy Loan, Timiza, HF Whizz)?',
 'C1_3': 'C1-3. Savings/keeping through mobile money account (e.g. MPESA, Airtel Money, TCash, Tangaza, MobiKash, Equitel)',
 'C1_4': 'C1-4. Savings at a Sacco / Savings and Credit Cooperative organisation',
 'C1_5': 'C1-5. Savings at a group or chama',
 'C1_6': 'C1-6. Savings with a group of friends',
 'C1_7': 'C1-7. Savings given to a family or friend to keep',
 'C1_8': 'C1-8. Savings you keep in a secret hiding place',
 'C1_9': 'C1-9. Registered on Mobile money (e.g. MPESA, Airtel Money, TCash, Tangaza, Equitel)',
 'C1_10': 'C1_10. Registered on Mobile bank (e.g. Mshwari , KCB MPesa, MCoop cash, Eazzy Loan, Timiza, HF Whizz)',
 'C1_11': 'C1_11. Personal loan/business loan from a bank',
 'C1_12': 'C1_12. Loan from mobile banking (e.g. Mshwari , KCB MPesa, MCoop cash, Eazzy Loan, Timiza, HF Whizz, Stawi loan, M-fanisi)',
 'C1_13': 'C1_13. Loan from mobile money provider (e.g Fuliza loan)',
 'C1_14': 'C1_14. Loan at a Sacco / Savings and Credit Cooperative organisation',
 'C1_15': 'C1_15. Loan from a microfinance institution',
 'C1_16': 'C1_16. Loan from Shylocks / Loan Sharks / Money Lenders / Money Merchants that are not from your phone (e.g. Platinum, Ngao, etc.)',
 'C1_17': 'C1_17. Loan from a group/chama',
 'C1_18': 'C1_18. Loan from a government institution for education, agriculture or devt',
 'C1_19': 'C1_19. Loan from an employer',
 'C1_20': 'C1-20. Loan from family/friend/neighbour',
 'C1_21': 'C1-21. Cash loan from shopkeeper',
 'C1_22': 'C1-22. Taking goods and services on credit from a shopkeeper',
 'C1_23': 'C1-23 Digital loans that you get through the phone that you download through apps (e.g. Branch, Tala, Utunzi, Haraka loans, etc.)',
 'C1_24': 'C1-24 Loan / credits from buyer of your harvest / supplier of agricultural inputs (e.g. coffee, tea, sugarcane, tobacco, vegetables)',
 'C1_25': 'C1-25. Hire purchase (e.g. KuKopesha, Diamond Trust, Kenya Credit Traders (KCT), Synergy, One Africa Capital, Tuskys)',
 'C1_26': 'C1-26. Loan from Insurance',
 'C1_27': 'C1-27. Loan to buy / build a house (mortgage), or to buy land from a bank / building society or Sacco/Insurance/Government',
 'C1_28': 'C1-28. Current account - with a cheque book/ Transactional acc',
 'C1_29': 'C1-29. Postbank account',
 'C1_30': 'C1-30. Bank account for savings or investment (which pays interest)',
 'C1_31': 'C1-31. Bank account for everyday needs but no cheque book',
 'C1_32': 'C1-32. Bank/ Micro finance bank Overdraft',
 'C1_33': 'C1-33. Debit Card (use on ATM, POS to pay)',
 'C1_34': 'C1-34. Credit card',
 'C1_35': 'C1-35. Shares and/or stocks',
 'C1_36': 'C1-36. T- Bills and Bonds, including M-Akiba',
 'C1_37': 'C1-37. Mutual Funds/ Unit Trust/ Real Estate Investment Trusts (REITs)/Derivatives',
 'C1_38': 'C1-38. Motor insurance (car,motorbike,tuktuks)',
 'C1_39': 'C1-39. Home, building or contents insurance',
 'C1_40': 'C1-40. Crop insurance',
 'C1_41': 'C1-41. Livestock insurance',
 'C1_42': 'C1-42. NHIF',
 'C1_43': 'C1-43. Other medical/health insurance policy, NOT NHIF',
 'C1_44': 'C1-44. Life insurance policy',
 'C1_45': 'C1-45. Education policy',
 'C1_46': "C1_46. Workmen's compensation(WIBA)",
 'C1_47': 'C1-47. Other insurance',
 'C1_47a': 'C1_47a Private insurance,  not specified',
 'C1_47b': 'C1_47b Last expense',
 'C1_47c': 'C1_47c Business/ivestment insurance',
 'C1_48': 'C1-48. NSSF',
 'C1_49': 'C1-49. Employment/ Occupation pension scheme, NOT NSSF',
 'C1_50': 'C1-50. Mbao pension plan',
 'C1_51': 'C1-51. Individual Pension Plan, NOT Mbao',
 'C1_52': 'C1-52. Other Retirement/ pension plan',
 'C1_53': 'C1-53. Digital/crypto/community-currencies',
 'C2_2': 'C2-2. Savings through mobile banking',
 'C2_3': 'C2_3. Savings through mobile money provider',
 'C2_9': 'C2_9. Registered on Mobile money',
 'C2_10': 'C2_10. Registered on Mobile banking',
 'C2_12': 'C2_12. Loan from mobile banking',
 'C2_13': 'C2_13. Mobile money loans (e.g Fuliza). Did you use this in the last 12 months?',
 'C3_1': 'C3_1. Capital Markets Intermediary',
 'C3_2': 'C3_2. Pensions',
 'C4': 'QC4. Trusted financial provider',
 'C5': 'C5. Highest Interest Rate Perception',
 'D1i__1': 'D1i__1  You would like to be a member of a Pension Scheme but cannot afford it',
 'D1i__2': 'D1i__2  You do not know how to become a member',
 'D1i__3': 'D1i__3  Pension Schemes are dishonest',
 'D1i__4': 'D1i__4  You do not need Pension because your family, friends, groups of friends, chama and relatives will help you in old age',
 'D1i__5': 'D1i__5  You do not need pension because you have saved in other financial institutions/assets for your old age',
 'D1i__6': 'D1i__6  You do not need Pension because I have educated my children and they will take care of me in old age',
 'D1i__7': 'D1i__7  Religious/cultural reasons',
 'D1i__8': 'D1i__8  You do not see the benefits of saving for retirement',
 'D1i__9': 'D1i__9  You do not know about pensions',
 'D1i__10': 'D1i__10  You have or use pension of another person e.g. your parent, spouse/partner or through a group policy',
 'D1i__11': 'D1i__11  They refused to pay my pension',
 'D1i__12': 'D1i__12  You do not need pension because in your family tree people die before reaching retirement age',
 'D1i__13': 'D1i__13  Other (SPECIFY)',
 'D1i__14': 'D1i__14  Already accessed my pension money',
 'D1i__15': 'D1i__15  Lack of National ID/ under 18 yrs of age/student',
 'D1i__16': 'D1i__16  Used to contribute but lost job / stopped working',
 'D1i__17': "D1i__17  Not interested/ Haven't given pensions a thought",
 'D1i__18': 'D1i__18  Too old for pension',
 'D1i__19': 'D1i__19  In the procees/lost card',
 'D1i__98': "D1i__98  Don't know (DO NOT READ OUT)",
 'D1i__99': 'D1i__99  Refused to Answer (DO NOT READ OUT)',
 'D1i_i': 'D1i_i. Other Pension specify',
 'D1ii': 'D1ii_a Enough money during retirement to meet needs',
 'D1iib': 'D1ii_b Pension enough to meet needs on retirement',
 'D1iii': 'D1iii . Access pension before retirement',
 'D1A': "D1A. Somebody Else's Insurance",
 'D1B__1': 'D1B__1  You would like to have insurance but cannot afford it',
 'D1B__2': 'D1B__2  Trying to buy health or life insurance for yourself or your family can bring bad luck',
 'D1B__3': 'D1B__3  You do not know where to get it from',
 'D1B__4': 'D1B__4  Insurance companies are dishonest',
 'D1B__5': 'D1B__5  Insurance agents are dishonest',
 'D1B__6': 'D1B__6  You do not need insurance because your family, friends, groups of friends, chama and relatives help you when you are in need',
 'D1B__7': 'D1B__7  You do not have insurance because you save for emergencies',
 'D1B__8': 'D1B__8  Religious reasons /cultural reasons',
 'D1B__9': 'D1B__9  You do not see the benefits of having insurance',
 'D1B__10': 'D1B__10  You do not know about insurance',
 'D1B__11': 'D1B__11  You have or use insurance through another person e.g. your parent, spouse/partner or through a group policy',
 'D1B__12': 'D1B__12  They refused to pay my insurance claim',
 'D1B__14': 'D1B__14  ILack of identification document/ necessary documentation to register E.g. ID, KRA pin/student',
 'D1B__98': "D1B__98  Don't know(DO NOT READ OUT)",
 'D1B__99': 'D1B__99  Refused to Answer (DO NOT READ OUT)',
 'D1Bi': 'D1Bi  D1Bi. Why Don’t Have Insurance In Own Name - other',

In [13]:
# Load the third sheet
df = pd.read_excel("../data/raw/finaccess_2021_microdata.xlsx", sheet_name="Variable Values",nrows=1000, engine="openpyxl",header=1)
df.head()

    Value Unnamed: 1       Label
0  County          1     Mombasa
1     NaN          2       Kwale
2     NaN          3      Kilifi
3     NaN          4  Tana River
4     NaN          5        Lamu

In [14]:
df.shape

(1000, 3)

In [15]:
df.columns

Index(['Value', 'Unnamed: 1', 'Label'], dtype='object')

In [16]:
df.describe()

         Value Unnamed: 1 Label
count      232       1000  1000
unique     232         63   269
top     County          1    No
freq         1        213   134

## Variable Values Sheet Description
This sheet explains the coded values used within variables. It maps numerical or categorical codes to their actual meanings.